### ISSUE TITLE
Found this to be a little confusing

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/collaborating-objects-review#3]
Not sure if this is the right place for this, but I had a hard time following this video. I think a crash course on how to create Rspec tests before this would have been helpful for me, because even though we've been using them to make our code work so far, this overview is losing me with the details of building the tests themselves. Basically I'm struggling to understand the main object concepts because I'm trying to make sense of how to write Rspecs.

**Comment by gooryalhamed** [comment]
Hi Pletcher, I agree with you. This video supposed to be about collaborating objects not about writing Rspecs.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestions.

Generally speaking, the videos are meant as material to augment the written curriculum and should be viewed as optional. After hearing feedback from students wanting more videos we have placed a few throughout the course. Because every student learns differently though, these videos are simply another way to deepen your understanding. If it doesn't work for you that's no problem. To better communicate this we will add a disclaimer explaining all of this to the lessons containing video resources. The written curriculum will independently cover all the required knowledge. Of course, we will continue to improve the videos and written material.

If, after reviewing the written curriculum, you still feel that there is a gap, feel free to reopen the issue.

As always, thanks for contributing! 💙
