### ISSUE TITLE
Consider adding some context

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/collaborating-objects-review#4]
Great video! Useful for both substance and process.

Do to some minor apparent curricular changes or differences between the in-person and online program, I might consider prefacing the video with a little explanatory text on:
- tap
- let
- setting up a console
- multi-selecting copies of the same word w/o using mouse

...since they all seem quite useful.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestions.

Generally speaking, the videos are meant as material to augment the written curriculum and should be viewed as optional. After hearing feedback from students wanting more videos we have placed a few throughout the course. Because every student learns differently though, these videos are simply another way to deepen your understanding. If it doesn't work for you that's no problem. To better communicate this we will add a disclaimer explaining all of this to the lessons containing video resources. The written curriculum will independently cover all the required knowledge. Of course, we will continue to improve the videos and written material.

If, after reviewing the written curriculum, you still feel that there is a gap, feel free to reopen the issue.

As always, thanks for contributing! 💙
